### ISSUE TITLE
Decide on tech stack for site

### ISSUE THREAD

**Issue by justincely** [justincely/pipsplace#1]
MVP we want for this is probably:

1. Basic property listing stuff (photos, descriptions, maybe videos)
2. calendar that allows folks to see who's there and book time
3. Login with Google oauth rather than username/password so it's easy for non tech-savvy family. 

We'll need to decide on what to use for server and front-end.

**Comment by justincely** [comment]
TBH #3 isn't entirely a blocker though - it's possible to add this in at the proxy layer, but it would be way easier to just use something that has a direct integration.

**Comment by justincely** [comment]
Something in python would probably be simplest - i'm sure there's integrations with all this stuff, but we can also balance how much you want to learn something like go to try to do it.

**Comment by ZachSellman** [comment]
I'm good to do either Python or Go; was leaning more towards the latter for good practice but whichever you'd prefer is fine by me. As far as the calendar portion goes I'm curious if there is a way to implement a Google calendar situation seeing as we want people to use Google oauth anyways?

**Comment by justincely** [comment]
Using Go is fine - but then you'll actually need to code in Javascript for the front end unless you can find a Go framework that includes that.  So that'll be more of a challenge; depends on how much work you want to put in.  

There are google calendar APIs we could certainly use if we want.  Otherwise we could just use some basic calendar feature like https://github.com/Kartones/flask-calendar

**Comment by justincely** [comment]
I'd say take a little bit of time and see if Go+framework or Go+JS seems doable/something you want to do.  And if not, lets go with python.

**Comment by ZachSellman** [comment]
That's true... Honestly wouldn't be the worst thing to be able to add JS to my resume even if it's just basic knowledge. I'll check out some for a bit and see.

**Comment by ZachSellman** [comment]
I think we're gonna take the big swing and go for a Go server with the usual html/css/js frontend. The website itself isn't super complex as we've described it so far, so it'll be a good learning opportunity to make use of all of this.

**Comment by ZachSellman** [comment]
Looks like google oauth implementation should be a breeze (famous last words I'm sure). https://www.loginradius.com/blog/engineering/google-authentication-with-golang-and-goth/

**Comment by justincely** [comment]
Hah ok, well lets do it then!
