### ISSUE TITLE
build_and_deploy doesn't function properly

### ISSUE THREAD

**Issue by ZachSellman** [justincely/pipsplace#19]
Currently shows one error and one warning:

Error: buildx failed with: Error: failed to solve: failed to push latest: server message: insufficient_scope: authorization failed
Warning: Node.js 12 actions are deprecated. Please update the following to use Node.js 16: actions/checkout@v2

**Comment by justincely** [comment]
mhmm interesting

**Comment by justincely** [comment]
Still not working.  compare https://github.com/justincely/pipsplace/actions/runs/5300063445/workflow#L39  and https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub

**Comment by justincely** [comment]
I'll give you a hint.  What image tag is it trying to push.
