### ISSUE TITLE
Build skeleton backend

### ISSUE THREAD

**Issue by justincely** [justincely/pipsplace#2]
Just the basic server so we can do simple deployments.  

So a basic go server:

1. Runs on a configurable host/port
2. Logs some basic bits like what host:port you chose
3. Serves a basic REST endpoint for health checks.  e.g. an HTTP GET to `/health` will return 200 OK status with a JSON payload of `{"status": "serving"}`

**Comment by ZachSellman** [comment]
For logs you mean write to a log file correct?

**Comment by justincely** [comment]
for the first iteration stdout is probably fine.  If you use something like the zap library it'll give plenty of options to change it to log file or something later.
